import { NextRequest, NextResponse } from "next/server";
import { providers, ProviderName, redirectUri } from "@/lib/providers";

/**
 * Opens the provider's consent screen.
 *
 * The `state` nonce is generated by the Mac app and echoed all the way back to it,
 * so a callback nobody asked for is ignored rather than trusted.
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ provider: string }> },
) {
  const { provider } = await params;
  const config = providers[provider as ProviderName];
  if (!config) {
    return NextResponse.json({ error: "Unknown provider" }, { status: 404 });
  }

  const clientId = config.clientId();
  if (!clientId) {
    return NextResponse.json(
      { error: `${provider} is not configured on the server` },
      { status: 500 },
    );
  }

  const state = request.nextUrl.searchParams.get("state");
  if (!state) {
    return NextResponse.json({ error: "Missing state" }, { status: 400 });
  }

  const url = new URL(config.authorizeUrl);
  url.searchParams.set("client_id", clientId);
  url.searchParams.set("redirect_uri", redirectUri(provider as ProviderName));
  url.searchParams.set("state", state);
  for (const [key, value] of Object.entries(config.authorizeParams)) {
    url.searchParams.set(key, value);
  }

  return NextResponse.redirect(url.toString());
}
